color: cyan
fieldLayouts:
  238507e3-9c50-419a-905a-2569586aa8b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-20T19:25:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a17267ea-ccc9-4676-8ba5-2e7f82ca0bbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-20T19:28:14+00:00'
            elementCondition: null
            fieldUid: 69cf82d5-482d-4b1b-8a34-72cb92965bcf # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4151fbe2-8252-44d2-aab5-0abf61b1dc12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-20T19:28:14+00:00'
            elementCondition: null
            fieldUid: c99ffa0f-b08c-4d6d-8dfe-410aaa5ccd99 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5da727e9-a929-4c64-9b65-de690945636f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-20T19:37:06+00:00'
            elementCondition: null
            fieldUid: bcf1c20d-fef6-4456-a477-f4de83877e75 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b37cdba4-7db3-499c-9359-82e0df04f120
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-21T05:11:32+00:00'
            elementCondition: null
            fieldUid: afb8dc04-ca52-442f-ae72-8a8be4daef58 # Product Highlights
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39663fcd-8055-43d7-9ae5-702e90b0c65c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a23211a5-3baa-4339-87cd-ffc8f2d2dd2c
        userCondition: null
handle: product
hasTitleField: true
icon: boot-heeled
name: Product
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
