altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  af45e2e3-b911-4ca5-81be-4cbc21cfe7b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-20T19:27:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 50911fbb-019f-49c7-8f84-701a0fe35551
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a64a5d6-c0ad-4703-b9ea-613fadf074bf
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: imageTransforms
transformSubpath: ''
